name: Postman CI Lista Cadastro

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Verificar versão do Newman e Node.js
    - name: Check version Newman and Node
      run: |
        newman --version
        node --version
    # Instalar newman-reporter-htmlextra
    - name: Install Newman-Reporter-HtmlExtra
      run:  sudo npm install -g newman-reporter-htmlextra
    # Executar a coleção com ambiente especificado
    - name: Execute collection
      run: newman run  ./collection.json -e ./environment.json -g ./global.json --delay-request 1 reporters cli, -r htmlextra --reporter-htmlextra-export ./results/report.html
    # Carregar relatório de teste
    - name: Upload Test Report
    
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: ./result/Result.html
